---
name: Deploy Scaleway serverless container

on:
  push:
    branches:
      - 'main'

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        id: prepare
        uses: actions/checkout@v4

      - name: Login to Scaleway Website container registry
        id: login
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.SCW_CONTAINER_REGISTRY }}
          username: _json_key
          password: ${{ secrets.SCW_SECRET_KEY }}

      - name: Build and push Website Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.SCW_CONTAINER_REGISTRY }}/website:latest
