---
name: Validate feature branch

on:
  push:
    branches:
      - 'build/*'
      - 'chore/*'
      - 'ci/*'
      - 'docs/*'
      - 'feat/*'
      - 'fix/*'
      - 'perf/*'
      - 'refactor/*'
      - 'revert/*'
      - 'style/*'
      - 'test/*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Build Website Docker image
        uses: docker/build-push-action@v6
        with:
          push: false
